name: Node.js CI & Deployment

on:
  push:
    branches: [ main, feat/migrate-react-flask ]
  pull_request:
    branches: [ main, feat/migrate-react-flask ]

jobs:
  build:
    runs-on: [self-hosted, example2]

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install dependencies
      working-directory: ./client
      run: pnpm install --no-strict-peer-dependencies
      
    - name: Build
      working-directory: ./client
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GOOGLE_BOOKS_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
      run: pnpm run build

  deploy:
    needs: build
    runs-on: [self-hosted, example2]
 
    steps:
    - name: Pull latest changes
      run: |
        git pull origin ${{ github.ref }}
        
    - name: Setup environment variables
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
        echo "GOOGLE_BOOKS_API_KEY=${{ secrets.GOOGLE_BOOKS_API_KEY }}" >> .env
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
        
    - name: Stop PM2 processes
      run: |
        pm2 delete all || true
        
    - name: Start PM2 processes
      run: |
        cd server && pm2 start app.py --name api --interpreter python3
        cd ../client && pm2 serve dist 3000 --name client --spa
        
    - name: Setup Nginx configuration
      run: |
        # Ensure nginx directories exist
        sudo mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled
        
        # Remove default nginx site if it exists
        sudo rm -f /etc/nginx/sites-enabled/default
        
        # Copy our nginx configuration
        sudo cp .nginx/inkreads.conf /etc/nginx/sites-available/inkreads.conf
        sudo ln -sf /etc/nginx/sites-available/inkreads.conf /etc/nginx/sites-enabled/inkreads.conf
        
        # Test nginx configuration
        sudo nginx -t
        
        # Restart nginx
        sudo systemctl restart nginx || sudo service nginx restart
        
    - name: Verify services
      run: |
        echo "Checking PM2 processes..."
        pm2 list
        
        echo "Checking Nginx status..."
        sudo systemctl status nginx || sudo service nginx status
        
        echo "Checking API endpoint..."
        curl -I https://theinkreads.com/api || true
        
        echo "Checking main site..."
        curl -I https://theinkreads.com || true
        
    - name: Complete job
      run: |
        echo "Deployment completed successfully" 