name: Node.js CI

on:
  push:
    branches: ["stable_server"]

jobs:
  build:
    runs-on: [self-hosted, example]

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm ci --legacy-peer-deps
      - run: pnpm run build --if-present
      - run: pm2 restart example
